# Generated by Django 4.2.13 on 2024-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tva',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
