# Generated by Django 4.2.10 on 2024-03-03 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avances',
            options={'verbose_name': 'Avances', 'verbose_name_plural': 'Avances'},
        ),
        migrations.AlterModelOptions(
            name='bonlivraison',
            options={'verbose_name': 'Bon de livraison', 'verbose_name_plural': 'Bon de livraison'},
        ),
        migrations.AlterModelOptions(
            name='camion',
            options={'verbose_name': 'Camions', 'verbose_name_plural': 'Camions'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='conducteur',
            options={'verbose_name': 'Conducteur', 'verbose_name_plural': 'Conducteur'},
        ),
        migrations.AlterModelOptions(
            name='conduire',
            options={'verbose_name': 'Conduire', 'verbose_name_plural': 'Conduire'},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'Contrats', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='detailfacture',
            options={'verbose_name': 'Details', 'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='dqe',
            options={'verbose_name': 'DQE', 'verbose_name_plural': 'DQE'},
        ),
        migrations.AlterModelOptions(
            name='encaissement',
            options={'verbose_name': 'Encaissements', 'verbose_name_plural': 'Encaissements'},
        ),
        migrations.AlterModelOptions(
            name='factures',
            options={'verbose_name': 'Factures', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='historicalavances',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Avances', 'verbose_name_plural': 'historical Avances'},
        ),
        migrations.AlterModelOptions(
            name='historicalbonlivraison',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bon de livraison', 'verbose_name_plural': 'historical Bon de livraison'},
        ),
        migrations.AlterModelOptions(
            name='historicalcamion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Camions', 'verbose_name_plural': 'historical Camions'},
        ),
        migrations.AlterModelOptions(
            name='historicalclients',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Clients', 'verbose_name_plural': 'historical Clients'},
        ),
        migrations.AlterModelOptions(
            name='historicalconducteur',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Conducteur', 'verbose_name_plural': 'historical Conducteur'},
        ),
        migrations.AlterModelOptions(
            name='historicalconduire',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Conduire', 'verbose_name_plural': 'historical Conduire'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontrat',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Contrats', 'verbose_name_plural': 'historical Contrats'},
        ),
        migrations.AlterModelOptions(
            name='historicaldqe',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical DQE', 'verbose_name_plural': 'historical DQE'},
        ),
        migrations.AlterModelOptions(
            name='historicalencaissement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Encaissements', 'verbose_name_plural': 'historical Encaissements'},
        ),
        migrations.AlterModelOptions(
            name='historicalfactures',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Factures', 'verbose_name_plural': 'historical Factures'},
        ),
        migrations.AlterModelOptions(
            name='historicalmodepaiement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mode de Paiement', 'verbose_name_plural': 'historical Mode de Paiement'},
        ),
        migrations.AlterModelOptions(
            name='historicalods',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ODS', 'verbose_name_plural': 'historical ODS'},
        ),
        migrations.AlterModelOptions(
            name='historicalparametres',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Parametres', 'verbose_name_plural': 'historical Parametres'},
        ),
        migrations.AlterModelOptions(
            name='historicalplaning',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Planing', 'verbose_name_plural': 'historical Planing'},
        ),
        migrations.AlterModelOptions(
            name='historicalprixproduit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prix des Produits', 'verbose_name_plural': 'historical Prix des Produits'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduits',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produits', 'verbose_name_plural': 'historical Produits'},
        ),
        migrations.AlterModelOptions(
            name='historicalunite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unités', 'verbose_name_plural': 'historical Unités'},
        ),
        migrations.AlterModelOptions(
            name='historicalunitemesure',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unités de mesure', 'verbose_name_plural': 'historical Unités de mesure'},
        ),
        migrations.AlterModelOptions(
            name='modepaiement',
            options={'verbose_name': 'Mode de Paiement', 'verbose_name_plural': 'Mode de Paiement'},
        ),
        migrations.AlterModelOptions(
            name='ods',
            options={'verbose_name': 'ODS', 'verbose_name_plural': 'ODS'},
        ),
        migrations.AlterModelOptions(
            name='parametres',
            options={'verbose_name': 'Parametres', 'verbose_name_plural': 'Parametres'},
        ),
        migrations.AlterModelOptions(
            name='planing',
            options={'verbose_name': 'Planing', 'verbose_name_plural': 'Planing'},
        ),
        migrations.AlterModelOptions(
            name='prixproduit',
            options={'verbose_name': 'Prix des Produits', 'verbose_name_plural': 'Prix des Produits'},
        ),
        migrations.AlterModelOptions(
            name='produits',
            options={'verbose_name': 'Produits', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='unite',
            options={'verbose_name': 'Unités', 'verbose_name_plural': 'Unités'},
        ),
        migrations.AlterModelOptions(
            name='unitemesure',
            options={'verbose_name': 'Unités de mesure', 'verbose_name_plural': 'Unités de mesure'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.clients', verbose_name='Est client de'),
        ),
        migrations.AlterField(
            model_name='historicalclients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.clients', verbose_name='Est client de'),
        ),
        migrations.AlterField(
            model_name='historicalprixproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
    ]
