# Generated by Django 4.2.13 on 2024-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='camion',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='detailfacture',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='factures',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='planing',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='produits',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='unitemesure',
            name='user_id',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
