# Generated by Django 4.2.10 on 2024-03-19 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='poids',
            new_name='tare',
        ),
        migrations.RenameField(
            model_name='historicalcamion',
            old_name='poids',
            new_name='tare',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='qte_mois',
        ),
        migrations.RemoveField(
            model_name='historicalbonlivraison',
            name='qte_mois',
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='numero_permis_c',
            field=models.CharField(max_length=500, null=True, verbose_name='N° P.Conduire'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='ptc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PTC'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='numero_permis_c',
            field=models.CharField(max_length=500, null=True, verbose_name='N° P.Conduire'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='ptc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PTC'),
        ),
    ]
