# Generated by Django 4.2.10 on 2024-03-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplaning',
            name='qte_cumule',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='qte_cumule',
        ),
    ]
