# Generated by Django 4.2.10 on 2024-03-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduits',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='historicalproduits',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='unite',
        ),
    ]
