# Generated by Django 4.2.10 on 2024-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='unite',
        ),
    ]
