# Generated by Django 4.2.13 on 2024-07-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prixproduit',
            unique_together={('produit', 'u', 'prix_unitaire', 'type_prix', 'id')},
        ),
    ]
