# Generated by Django 4.2.13 on 2024-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encaissement',
            options={'verbose_name': 'Encaissements', 'verbose_name_plural': 'Encaissements'},
        ),
    ]
