# Generated by Django 4.2.13 on 2024-07-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='est_client_cosider',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='sous_client',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='type_client',
        ),
    ]
