# Generated by Django 4.2.13 on 2024-07-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQECumule',
            fields=[
                ('id', models.CharField(max_length=900, primary_key=True, serialize=False)),
                ('produit_id', models.CharField(max_length=500)),
                ('code_contrat', models.CharField(max_length=500)),
                ('qte', models.DecimalField(blank=True, db_column='Qte', decimal_places=3, max_digits=38, null=True)),
                ('avenant', models.IntegerField(blank=True, null=True)),
                ('contrat_id', models.CharField(blank=True, max_length=900, null=True)),
                ('prixproduit_id', models.CharField(blank=True, db_column='prixProduit_id', max_length=900, null=True)),
                ('rabais', models.DecimalField(blank=True, decimal_places=3, max_digits=38, null=True)),
                ('prix_transport', models.DecimalField(blank=True, decimal_places=3, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'DQE_View_Cumule',
                'managed': False,
            },
        ),
    ]
