# Generated by Django 4.2.10 on 2024-03-26 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('saisie_automatique', models.BooleanField(default=False, verbose_name='Saisie Automatique')),
                ('port', models.CharField(default='COM1', max_length=500, verbose_name='Port')),
                ('unite', models.ForeignKey(blank=True, db_column='unite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.unite', verbose_name='Unite')),
            ],
            options={
                'verbose_name': 'Configurations',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfigurations',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('saisie_automatique', models.BooleanField(default=False, verbose_name='Saisie Automatique')),
                ('port', models.CharField(default='COM1', max_length=500, verbose_name='Port')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unite', models.ForeignKey(blank=True, db_column='unite', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.unite', verbose_name='Unite')),
            ],
            options={
                'verbose_name': 'historical Configurations',
                'verbose_name_plural': 'historical Configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalparametres',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parametres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalParametres',
        ),
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
