# Generated by Django 4.2.10 on 2024-03-21 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
    ]
