# Generated by Django 4.2.13 on 2024-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_dqecumule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqe',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38),
        ),
    ]
