# Generated by Django 4.2.13 on 2024-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_remove_clients_est_client_cosider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tva',
            old_name='valeur',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='clients',
            name='raison_social',
            field=models.CharField(blank=True, db_column='Raison_Social', max_length=50, null=True, verbose_name='Raison Sociale'),
        ),
    ]
