# Generated by Django 4.2.10 on 2024-03-03 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_alter_avances_options_alter_bonlivraison_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (HT)'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (TTC)'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (HT)'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (TTC)'),
        ),
    ]
