# Generated by Django 4.2.10 on 2024-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_configurations_historicalconfigurations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='id',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False, verbose_name='N° BL'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=500, verbose_name='N° BL'),
        ),
    ]
