# Generated by Django 4.2.10 on 2024-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='date_cloture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de cloture'),
        ),
    ]
