# Generated by Django 4.2.10 on 2024-03-19 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_rename_poids_camion_tare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='tare',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tare'),
        ),
        migrations.AlterField(
            model_name='historicalcamion',
            name='tare',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tare'),
        ),
    ]
