# Generated by Django 4.2.10 on 2024-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_alter_detailfacture_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
