# Generated by Django 4.2.13 on 2024-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_alter_prixproduit_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=500)),
                ('est_bloquer', models.BooleanField(default=False, editable=False)),
                ('user_id', models.CharField(editable=False, max_length=500)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypeClient',
                'verbose_name_plural': 'TypeClient',
                'db_table': 'Type_Client',
            },
        ),
    ]
