# Generated by Django 4.2.10 on 2024-04-02 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0002_alter_detailfacture_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avances',
            name='remboursee',
        ),
        migrations.RemoveField(
            model_name='historicalavances',
            name='remboursee',
        ),
        migrations.AddField(
            model_name='avances',
            name='montant_restant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant restant de l'avance"),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='avance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.avances', verbose_name='Avance'),
        ),
        migrations.AddField(
            model_name='historicalavances',
            name='montant_restant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant restant de l'avance"),
        ),
        migrations.AddField(
            model_name='historicalencaissement',
            name='avance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.avances', verbose_name='Avance'),
        ),
    ]
