# Generated by Django 4.2.10 on 2024-03-26 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gc', '0002_rename_numero_facture_factures_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'unite')},
        ),
    ]
