# Generated by Django 4.2.10 on 2024-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_remove_avances_remboursee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avances',
            name='num_avance',
            field=models.PositiveIntegerField(default=0, verbose_name='Num avance'),
        ),
        migrations.AddField(
            model_name='historicalavances',
            name='num_avance',
            field=models.PositiveIntegerField(default=0, verbose_name='Num avance'),
        ),
        migrations.AlterUniqueTogether(
            name='avances',
            unique_together={('contrat', 'montant_avance')},
        ),
    ]
