# Generated by Django 4.2.13 on 2024-07-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_typeclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.typeclient', verbose_name='Type'),
        ),
    ]
