# Generated by Django 4.2.10 on 2024-03-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_profile_historicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unite',
            field=models.ForeignKey(blank=True, db_column='Unité', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.unite', verbose_name='Unité'),
        ),
    ]
