# Generated by Django 4.2.10 on 2024-03-03 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_alter_contrat_montant_ht_alter_contrat_montant_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplaning',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré cumulée'),
        ),
        migrations.AddField(
            model_name='planing',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré cumulée'),
        ),
    ]
