# Generated by Django 4.2.10 on 2024-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_remove_bonlivraison_qte_precedent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraison',
            name='qte_cumule',
        ),
        migrations.RemoveField(
            model_name='historicalbonlivraison',
            name='qte_cumule',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='date',
            field=models.DateField(),
        ),
    ]
