# Generated by Django 4.2.13 on 2024-07-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_dqe_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='dqe',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.dqecumule', verbose_name='dqe'),
        ),
    ]
