# Generated by Django 4.2.10 on 2024-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0003_alter_camion_tare_alter_historicalcamion_tare'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='historicalfactures',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
