# Generated by Django 4.2.10 on 2024-02-28 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0004_historicalunite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cumulé'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='montant_mois',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant précedent'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cumulé'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='montant_mois',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AddField(
            model_name='historicalbonlivraison',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant précedent'),
        ),
    ]
