# Generated by Django 4.2.13 on 2024-07-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0004_clients_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=500)),
                ('est_bloquer', models.BooleanField(default=False, editable=False)),
                ('user_id', models.CharField(editable=False, max_length=500)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activite',
                'verbose_name_plural': 'Activite',
                'db_table': 'Activite',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.activite', verbose_name='Activite'),
        ),
    ]
