# Generated by Django 4.2.10 on 2024-03-21 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0004_factures_date_historicalfactures_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='factures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='historicalfactures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='historicalfactures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
    ]
