# Generated by Django 4.2.10 on 2024-03-03 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0004_historicalplaning_qte_cumule_planing_qte_cumule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='montant_avance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant de l'avance"),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cumulé'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='montant_mois',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant précedent'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité cumulé'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='qte_livre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='qte_precedent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité precedent'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='poids',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids net du camion'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (HT)'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (TTC)'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='rabais',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='tva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='montant_qte',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la quantité'),
        ),
        migrations.AlterField(
            model_name='dqe',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='montant_creance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en créance'),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant encaissé'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumulé'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_factureHT',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la facture en HT'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_factureTTC',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la facture en TTC'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_mois',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Precedent'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du rabais'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='historicalavances',
            name='montant_avance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant de l'avance"),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant cumulé'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='montant_mois',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant précedent'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité cumulé'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='qte_livre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='qte_precedent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité precedent'),
        ),
        migrations.AlterField(
            model_name='historicalcamion',
            name='poids',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids net du camion'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (HT)'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en (TTC)'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='rabais',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='tva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='historicaldqe',
            name='montant_qte',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la quantité'),
        ),
        migrations.AlterField(
            model_name='historicaldqe',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='historicalencaissement',
            name='montant_creance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant en créance'),
        ),
        migrations.AlterField(
            model_name='historicalencaissement',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant encaissé'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Cumulé'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_factureHT',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la facture en HT'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_factureTTC',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la facture en TTC'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_mois',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du Mois'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Precedent'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du rabais'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='historicalplaning',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré cumulée'),
        ),
        migrations.AlterField(
            model_name='historicalplaning',
            name='qte_livre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré'),
        ),
        migrations.AlterField(
            model_name='historicalprixproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré cumulée'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='qte_livre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité à livré'),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
    ]
