# Generated by Django 4.2.10 on 2024-03-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_remove_bonlivraison_montant_mois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraison',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='montant_precedent',
        ),
        migrations.RemoveField(
            model_name='historicalbonlivraison',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='historicalbonlivraison',
            name='montant_precedent',
        ),
    ]
