# Generated by Django 4.2.13 on 2024-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_activite_clients_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ville',
            field=models.CharField(db_column='ville', default='', max_length=500, verbose_name='Ville'),
        ),
    ]
