# Generated by Django 4.2.10 on 2024-04-02 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_remove_avances_montant_restant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avances',
            name='montant_restant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant restant de l'avance"),
        ),
        migrations.AddField(
            model_name='historicalavances',
            name='montant_restant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant restant de l'avance"),
        ),
    ]
