# Generated by Django 4.2.10 on 2024-03-03 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_alter_avances_montant_avance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonlivraison',
            old_name='qte_livre',
            new_name='qte_mois',
        ),
        migrations.RenameField(
            model_name='historicalbonlivraison',
            old_name='qte_livre',
            new_name='qte_mois',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité cumulé'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='qte_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité precedent'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='qte_cumule',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité cumulé'),
        ),
        migrations.AlterField(
            model_name='historicalbonlivraison',
            name='qte_precedent',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité precedent'),
        ),
        migrations.AlterUniqueTogether(
            name='bonlivraison',
            unique_together={('contrat', 'dqe', 'date')},
        ),
    ]
