# Generated by Django 4.2.10 on 2024-03-21 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_factures_montant_rb_factures_montant_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Rabais'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant RG'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_rb',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Rabais'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='montant_rg',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant RG'),
        ),
    ]
