# Generated by Django 4.2.10 on 2024-02-29 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0005_bonlivraison_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='rg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AddField(
            model_name='historicalcontrat',
            name='rg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais'),
        ),
        migrations.AddField(
            model_name='historicalparametres',
            name='port',
            field=models.CharField(default='COM1', max_length=500, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='parametres',
            name='port',
            field=models.CharField(default='COM1', max_length=500, verbose_name='Port'),
        ),
    ]
