# Generated by Django 4.2.10 on 2024-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0006_avances_montant_restant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avances',
            name='num_avance',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Num avance'),
        ),
        migrations.AlterField(
            model_name='historicalavances',
            name='num_avance',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Num avance'),
        ),
        migrations.DeleteModel(
            name='CumuleAvance',
        ),
    ]
