# Generated by Django 4.2.10 on 2024-03-25 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gc', '0006_bonlivraison_unite_historicalbonlivraison_unite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqe',
            name='unite',
            field=models.ForeignKey(blank=True, db_column='Unité', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.unite', verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='dqe',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='historicaldqe',
            name='unite',
            field=models.ForeignKey(blank=True, db_column='Unité', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.unite', verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='historicaldqe',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
