# Generated by Django 4.2.13 on 2024-07-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0006_clients_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqe',
            name='qte',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, verbose_name='Quantité'),
        ),
        migrations.AlterModelTable(
            name='dqecumule',
            table='DQE_View_Cumule_2',
        ),
    ]
