# Generated by Django 4.2.10 on 2024-03-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0006_alter_factures_montant_rb_alter_factures_montant_rg_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalFactures',
        ),
    ]
