# Generated by Django 4.2.10 on 2024-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0006_remove_bonlivraison_montant_cumule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_factureHT',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_factureTTC',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_mois',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_precedent',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_rb',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='montant_rg',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='numero_situtation',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_cumule',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_factureHT',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_factureTTC',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_mois',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_precedent',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_rb',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='montant_rg',
        ),
        migrations.RemoveField(
            model_name='historicalfactures',
            name='numero_situtation',
        ),
        migrations.AlterField(
            model_name='factures',
            name='numero_facture',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Numero de facture'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='numero_facture',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Numero de facture'),
        ),
    ]
