# Generated by Django 4.2.10 on 2024-03-03 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gc', '0006_contrat_rg_historicalcontrat_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='validite',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Durée de validité'),
        ),
        migrations.AddField(
            model_name='historicalcontrat',
            name='validite',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Durée de validité'),
        ),
        migrations.CreateModel(
            name='HistoricalAvances',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('montant_avance', models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant de l'avance")),
                ('remboursee', models.BooleanField(default=False, editable=False, verbose_name='Est remboursée')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.contrat', verbose_name='Contrat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical avances',
                'verbose_name_plural': 'historical avancess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('montant_avance', models.DecimalField(decimal_places=2, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant de l'avance")),
                ('remboursee', models.BooleanField(default=False, editable=False, verbose_name='Est remboursée')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.contrat', verbose_name='Contrat')),
            ],
        ),
    ]
