# Generated by Django 4.2.13 on 2024-07-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0007_alter_dqe_qte_alter_dqecumule_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqe',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.contrat', verbose_name='Contrat'),
        ),
    ]
