# Generated by Django 4.2.10 on 2024-03-21 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0007_delete_historicalfactures'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='factures',
            name='montant_facture_ht',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Facture (en HT)'),
        ),
        migrations.AddField(
            model_name='factures',
            name='montant_facture_ttc',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=38, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant Facture (en TTC)'),
        ),
    ]
