# Generated by Django 4.2.10 on 2024-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0007_remove_factures_montant_cumule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='numero_facture',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False, verbose_name='Numero de facture'),
        ),
        migrations.AlterField(
            model_name='historicalfactures',
            name='numero_facture',
            field=models.CharField(db_index=True, editable=False, max_length=500, verbose_name='Numero de facture'),
        ),
    ]
