# Generated by Django 4.2.13 on 2024-07-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0008_alter_dqe_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='contrat',
            field=models.CharField(max_length=500, verbose_name='N° du contrat'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.contrat', verbose_name='Contrat'),
        ),
    ]
