# Generated by Django 4.2.10 on 2024-03-04 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0008_alter_factures_numero_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='dqe',
            name='montant_qte',
        ),
        migrations.RemoveField(
            model_name='encaissement',
            name='montant_creance',
        ),
        migrations.RemoveField(
            model_name='historicalcontrat',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='historicalcontrat',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='historicaldqe',
            name='montant_qte',
        ),
        migrations.RemoveField(
            model_name='historicalencaissement',
            name='montant_creance',
        ),
        migrations.AlterField(
            model_name='contrat',
            name='libelle',
            field=models.CharField(blank=True, db_column='libelle', max_length=500, verbose_name='libelle'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retenue de garantie'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='libelle',
            field=models.CharField(blank=True, db_column='libelle', max_length=500, verbose_name='libelle'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='rg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=38, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retenue de garantie'),
        ),
    ]
