# Generated by Django 4.2.10 on 2024-03-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gc', '0009_remove_contrat_montant_ht_remove_contrat_montant_ttc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('itemImageSrc', models.ImageField(blank=True, default='default.png', upload_to='Images/Images')),
                ('thumbnailImageSrc', models.CharField(max_length=300, null=True)),
                ('alt', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Parametres',
                'verbose_name_plural': 'Parametres',
            },
        ),
        migrations.CreateModel(
            name='HistoricalImages',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('itemImageSrc', models.TextField(blank=True, default='default.png', max_length=100)),
                ('thumbnailImageSrc', models.CharField(max_length=300, null=True)),
                ('alt', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Parametres',
                'verbose_name_plural': 'historical Parametres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
