# Generated by Django 4.2.13 on 2024-07-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0009_alter_bonlivraison_contrat_alter_planing_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factures',
            name='contrat',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.contrat', verbose_name='Contrat'),
        ),
    ]
