# Generated by Django 4.2.10 on 2024-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0010_images_historicalimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimages',
            name='itemImageSrc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='itemImageSrc',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
