# Generated by Django 4.2.13 on 2024-07-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0011_alter_factures_contrat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dqecumule',
            table='DQE_View_Cumule',
        ),
    ]
