# Generated by Django 4.2.13 on 2024-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0012_alter_dqecumule_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='dqe_init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.dqe', verbose_name='dqe'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='planing',
            name='dqe',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.dqecumule', verbose_name='dqe'),
        ),
    ]
