# Generated by Django 4.2.10 on 2024-03-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0012_alter_historicalimages_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='validite',
        ),
        migrations.RemoveField(
            model_name='historicalcontrat',
            name='validite',
        ),
    ]
