# Generated by Django 4.2.10 on 2024-03-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0014_contrat__validite_mois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='_validite_mois',
        ),
        migrations.RemoveField(
            model_name='historicalcontrat',
            name='_validite_mois',
        ),
    ]
