# Generated by Django 4.2.10 on 2024-03-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0015_remove_contrat__validite_mois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.clients', verbose_name='Est client'),
        ),
        migrations.AlterField(
            model_name='historicalclients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.clients', verbose_name='Est client'),
        ),
    ]
