# Generated by Django 4.2.10 on 2024-03-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gc', '0016_alter_clients_sous_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dqe',
            old_name='prixPrduit',
            new_name='prixProduit',
        ),
        migrations.RenameField(
            model_name='historicaldqe',
            old_name='prixPrduit',
            new_name='prixProduit',
        ),
        migrations.AlterField(
            model_name='clients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gc.clients', verbose_name='Est client de'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='id',
            field=models.CharField(db_column='code_contrat', max_length=500, primary_key=True, serialize=False, verbose_name='Code du contrat'),
        ),
        migrations.AlterField(
            model_name='historicalclients',
            name='sous_client',
            field=models.ForeignKey(blank=True, db_column='sous_client', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_gc.clients', verbose_name='Est client de'),
        ),
        migrations.AlterField(
            model_name='historicalcontrat',
            name='id',
            field=models.CharField(db_column='code_contrat', db_index=True, max_length=500, verbose_name='Code du contrat'),
        ),
    ]
